version: '3'
networks:
  app-connection:
    driver: bridge
services:
  server:
    build: ./server
    container_name: server-go
    ports:
      - 8000:4000
    networks: 
      - app-connection
  front:
    build: ./spa
    container_name: front-vue
    ports:
      - 8080:80
    depends_on:
      - server
    networks:
      - app-connection
