version: '3.9'
networks:
  app-connection:
    driver: bridge
services:
  server:
    build: ./server
    container_name: server-go
    image: alexitouno19/vuego-demoapp-server-go:latest
    ports:
      - 4000:4000
    networks: 
      - app-connection
    environment:
      - IPSTACK_API_KEY=${IPSTACK_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
  front:
    build: ./spa
    container_name: front-vue
    image: alexitouno19/vuego-demoapp-front-vue:latest
    ports:
      - 8000:80
    depends_on:
      - server
    networks:
      - app-connection
    environment:
      - VUE_APP_API_ENDPOINT=${VUE_APP_API_ENDPOINT}
